version: '3.8'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: frappe
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frappe:
    image: frappe/frappe-socketio:v15.18.0
    environment:
      - DB_HOST=db
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2
    volumes:
      - ./:/workspace/development/apps/street_meubilair
      - frappe_data:/workspace/development
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - db
      - redis
    working_dir: /workspace/development
    command: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
  redis_data:
  frappe_data: 